name: Run Unit Tests
"on": push
jobs:
  unit_test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run:  npm cis
      - run:  npm run build
      - run:  npm run test:unit
