name: Run Unit Tests
"on": push
jobs:
  unit_test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run:  npm ci
      - run:  npm run build
      - run:  npm run test:unit
      
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    
        with:
          name: JEST Tests           
          path: reports/jest-*.xml   
          reporter: jest-junit        
